# Generated by Django 5.1.3 on 2024-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration_Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decoration', models.CharField(choices=[(0, 'decoration_1'), (1, 'decoration_2'), (2, 'decoration_3')], max_length=1)),
            ],
        ),
    ]
