# Generated by Django 5.1.3 on 2024-12-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_decoration_choose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Decoration_Choose',
        ),
        migrations.AddField(
            model_name='post',
            name='decoration',
            field=models.IntegerField(default=0),
        ),
    ]
